{TWITTER_KEY: 'CGfnvcXfkoaDNm6ahYeLaA',
TWITTER_SECRET: 'IKVXzfGhTgoC3cWwZh5Y1y4BxThlT0NK3h8YmTJHrM',
OAUTH_TOKEN: '13936852-8xX5vZNLiU3pYEecOdGDT4ceebmnGIK9aDUpFzfrx',
OAUTH_TOKEN_SECRET: 'Pe8b11LRT034jwmFzIOZwgvSDGJf39rFs9AR7bNrM'}