{TWITTER_KEY: 'CGfnvcXfkoaDNm6ahYeLaA',
TWITTER_SECRET: 'IKVXzfGhTgoC3cWwZh5Y1y4BxThlT0NK3h8YmTJHrM',
OAUTH_TOKEN: '13936852-deIkjxJQpTHbwjStZo7Ftj27yDQWI3qEsvFMhFtIq',
OAUTH_TOKEN_SECRET: 'xbN8DHy9k8qLmlQIe7syh5ONDMG13byept1vfACM'}